version: "2"
services:
  kafka:
    image: spotify/kafkaproxy
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: 127.0.0.1 
      ADVERTISED_PORT: 9092 
      CONSUMER_THREADS: 1 
      TOPICS: my-topic,some-other-topic 
      ZK_CONNECT: kafka7zookeeper:2181/root/path
      GROUP_ID: mymirror 
